version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www/html
    expose:
      - 9000

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./backend:/var/www/html
